handle IllegalStateException on fragment
java.lang.IllegalStateException: Can not perform this
 action after onSaveInstanceState

One case is when you try to close the app and
open the bottom sheet.

Fix: open the bottom sheet only if the fragment
is added to the activity.

https://github.com/celzero/rethink-app/issues/663